---
- include_tasks: parse-container-status.yml
- name: Configure nginx server config file
  template:
    src: nginx-serve-content.conf
    dest: '{{ file_server_config }}'
    group: '{{ group }}'
    mode: 0660
    owner: '{{ user }}'
  notify:
    - reload nginx

- name: Start and enable docker service
  service:
    name: docker
    state: started
    enabled: true
