---
- include_tasks: parse-container-status.yml
- name: Configure nginx server config file
  template:
    src: nginx-serve-content.conf
    dest: '{{ file_server_config }}'
  notify:
    - reload nginx
