---
- name: Create project dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    group: '{{ group }}'
    owner: '{{ user }}'
  with_items:
    - '{{ dir_project }}'
    - '{{ dir_versions }}'

- name: Upload artifact
  copy:
    src: '{{ image }}'
    dest: '{{ file_image }}'
    force: false

- name: Import image
  docker_image:
    force_source: false
    force_tag: false
    load_path: '{{ file_image }}'
    name: '{{ project_name }}:{{ version }}'
    source: load
    tag: '{{ version }}'

- name: Start container
  register: container_status
  docker_container:
    env: '{{ env }}'
    image: '{{ project_name }}:{{ version }}'
    name: '{{ project_name }}'
    published_ports: all
    pull: false
    state: started
