---
- name: Configure local image path
  set_fact:
    file_image_local: '{{ playbook_dir }}/{{ project_name }}-{{ project_version }}.tar'
  when: not image

- name: Check local image archive
  delegate_to: 127.0.0.1
  stat:
    path: '{{ file_image_local }}'
    follow: true
  register: image_local_stat
  when: not image

- name: Build the image
  delegate_to: 127.0.0.1
  docker_image:
    archive_path: '{{ file_image_local }}'
    source: build
    name: '{{ project_name }}'
    tag: '{{ project_version }}'
    state: present
    build:
      path: '{{ playbook_dir }}'
  when: not image and not image_local_stat.stat.exists

- name: Create project dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    group: '{{ group }}'
    owner: '{{ user }}'
  with_items:
    - '{{ dir_project }}'
    - '{{ dir_versions }}'

- name: Upload artifact
  copy:
    src: '{{ file_image_local }}'
    dest: '{{ file_image }}'
    force: false

- name: Import image
  docker_image:
    force_source: false
    force_tag: false
    load_path: '{{ file_image }}'
    name: '{{ project_name }}:{{ project_version }}'
    source: load
    state: present
    tag: '{{ project_version }}'

- name: Start container
  register: container_status
  docker_container:
    env: '{{ env }}'
    image: '{{ project_name }}:{{ project_version }}'
    name: '{{ project_name }}'
    published_ports: all
    pull: false
    state: started
