---
- name: Configure images directory
  set_fact:
    dir_images: '{{ dir_project }}/versions'

- name: Configure paths
  set_fact:
    file_image: '{{ dir_images }}/{{ project_version }}.tar'
    file_image_local: '{{ image_local }}'

- include_tasks: build.yml
  when: not image_local

- name: Create project dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    group: '{{ group }}'
    owner: '{{ user }}'
  with_items:
    - '{{ dir_project }}'
    - '{{ dir_versions }}'

- name: List remote images
  find:
    paths: '{{ dir_images }}'
    recurse: true
  register: remote_images

- name: Filter old images
  set_fact:
    old_images: "{{ remote_images.files|sort(attribute='mtime')|map(attribute='path')|list }}"

- name: Delete old images
  file:
    state: absent
    path: "{{ item }}"
  loop: "{{ old_images[0:-3] }}"

- name: Upload artifact
  copy:
    src: '{{ file_image_local }}'
    dest: '{{ file_image }}'

- name: Import image
  docker_image:
    force_source: false
    force_tag: false
    load_path: '{{ file_image }}'
    name: '{{ project_name }}:{{ project_version }}'
    source: load
    state: present
    tag: '{{ project_version }}'

- name: Start container
  register: container_status
  docker_container:
    env: '{{ env }}'
    hostname: '{{ container_name }}'
    image: '{{ project_name }}:{{ project_version }}'
    name: '{{ container_name }}'
    published_ports: all
    pull: false
    restart_policy: unless-stopped
    state: started
