---
- name: Install system dependencies
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - nginx
      - docker.io
      - docker
      - python3-distutils
      - python3-docker
