---
- name: Check required variables
  assert:
    that:
      - project_port is defined
      - project_port != 0
      - project_version is defined
      - project_version != ""

- name: Configure paths
  set_fact:
    file_image: '{{ dir_project }}/versions/{{ project_version }}.tar'
    file_image_local: '{{ image }}'

- name: Install system dependencies
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - nginx
      - docker.io
      - docker
      - docker-compose
      - python3-distutils
      - python3-docker

- include_tasks: deploy.yml
- include_tasks: config.yml
