---
- name: dump
  debug:
    var: project_version
- name: Check required variables
  assert:
    that:
      - project_port is defined and project_port
      - project_version is defined and project_version

- name: Install system dependencies
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - nginx
      - docker.io
      - docker
      - docker-compose
      - python3-distutils
      - python3-docker

- include_tasks: deploy.yml
  when: not image_name

- include_tasks: pull.yml
  when: image_name is defined and image_name

- include_tasks: config.yml
