---
- name: Make project id environment safe
  set_fact:
    instance_id: 'docker-{{ project_name }}-{{ environment }}'

- name: Check required variables
  assert:
    that: "{{ item }} is defined"
  with_items:
    - admin_email
    - environment
    - port
    - server_names
    - version

- name: Configure directories
  set_fact:
    dir_project: '{{ projects_directory }}/{{ project_name }}'

- name: Configure paths
  set_fact:
    dir_versions: '{{ dir_project }}/versions'
    file_image: '{{ dir_project }}/versions/{{ version }}.tar'
    file_site_config: '/etc/nginx/sites-available/{{ instance_id }}.conf'

- include_tasks: deps.yml
- include_tasks: deploy.yml
- include_tasks: config.yml
