---
- name: Check required variables
  assert:
    that:
      - project_port > 0

- name: Install system dependencies
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - nginx
      - docker.io
      - docker
      - docker-compose
      - python3-distutils
      - python3-docker

- name: Set container name
  set_fact:
    container_name: '{{ project_name }}-{{ project_environment }}'

- include_tasks: deploy.yml
  when: state == 'present' and not image_name

- include_tasks: pull.yml
  when: state == 'present' and image_name

- include_tasks: config.yml
  when: state == 'present'

- include_tasks: not-present.yml
  when: state != 'present'
