---
- name: Stop container
  docker_container:
    env: '{{ env }}'
    image: '{{ project_name }}:{{ project_version }}'
    name: '{{ container_name }}'
    state: stopped
  when: state == 'disabled'

- name: Remove container
  docker_container:
    env: '{{ env }}'
    image: '{{ project_name }}:{{ project_version }}'
    name: '{{ container_name }}'
    state: absent
  when: state == 'absent'
