---
- name: Set port facts
  set_fact:
    container_networks: '{{ container_status.container.NetworkSettings.Networks }}'
    container_ports: '{{ container_status.container.NetworkSettings.Ports }}'

- name: Resolve networking
  set_fact:
    container_addr: '{{ container_networks[network_name].IPAddress }}'
