---
- name: Start container
  register: container_status
  docker_container:
    env: '{{ env }}'
    image: '{{ image_name }}:{{ project_version }}'
    name: '{{ container_name }}'
    published_ports: all
    state: started
