---
name: CD
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@0.0.1
        with:
          docker_version: 19
          docker_channel: stable
      - name: Install ansible
        run: apt-get install -y ansible
      - name: Install the role
        run: ansible-galaxy install practical-ansible.nginx_docker
      - name: Configure inventory
        run: echo "$[web]\n{{ secrets.DEPLOY_HOST }}" > inventory
      - name: Deploy the application
        run: ansible-playbook -i inventory playbook.yml
        env:
          ANALYTICS_CODE: ${{ secrets.ANALYTICS_CODE }}
