---
- name: start nginx
  become: true
  service:
    name: nginx
    state: started

- name: restart nginx
  become: true
  service:
    name: nginx
    state: restarted

- name: reload nginx
  become: true
  service:
    name: nginx
    state: reloaded
