---
- name: Deploy to testing Docker container
  hosts: test
  vars:
    server_names: 'wiki.localhost'
    image_name: requarks/wiki
    project_name: wiki-js
    project_version: '2'
    project_port: 3000
    use_ssl: false
  roles:
    - role: practical-ansible.nginx_docker
